In [1]:
import numpy as np

In [2]:
l = [1, 2, 3]

In [3]:
A = np.array(l)

In [4]:
L2 = [[1, 2], [3, 4]]
A2 = np.array([[1, 2],[3, 4]])

In [5]:
print(L2)
print(A2)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [6]:
# Arrays de ceros y unos

array_ceros = np.zeros((3, 3))
array_unos = np.ones((2,2))

In [7]:
print(f"Array de ceros: \n {array_ceros}")
print(f"Array de unos: \n {array_unos}")

Array de ceros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array de unos: 
 [[1. 1.]
 [1. 1.]]


In [8]:
# Arrays de rangos

array_rango = np.arange(10)

In [9]:
print(f"Array de rango: \n {array_rango}")

Array de rango: 
 [0 1 2 3 4 5 6 7 8 9]


In [10]:
# Arrays espaciados linealmente

array_espaciado = np.linspace(0, 1, num=5)

In [11]:
print(f"Array espaciado linealmente: \n {array_espaciado}")

Array espaciado linealmente: 
 [0.   0.25 0.5  0.75 1.  ]


In [12]:
# Matriz identidad

m_identidad = np.eye(4)

In [13]:
print(f"Matriz identidad: \n {m_identidad}")

Matriz identidad: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# Arrays con tipos de datos especificos

int_array = np.array([[1, 2], [3, 4]], dtype='int32')
float_array = np.array([[1, 2], [3, 4]], dtype='float32')

In [15]:
print(f"Array con valores enteros: \n {int_array}")
print(f"Array con valores flotantes: \n {float_array}")

Array con valores enteros: 
 [[1 2]
 [3 4]]
Array con valores flotantes: 
 [[1. 2.]
 [3. 4.]]
