In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
print(a[0])

1


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(b[-1, -1])

9


In [6]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
c[3:8]

array([3, 4, 5, 6, 7])

In [8]:
# Salto en array
# El ultimo valor dice de cuanto seran los saltos

c[::2]

array([0, 2, 4, 6, 8])

In [9]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(d[1:3, 1:4])

[[ 6  7  8]
 [10 11 12]]


In [11]:
print(d[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [12]:
e = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.array([1, 3, 5])

e[indices]

array([2, 4, 6])

In [13]:
f = np.array([1, -1, -2, 3, -3, 3])

In [14]:
print(f)

[ 1 -1 -2  3 -3  3]


In [15]:
condition = f > 0
condition

array([ True, False, False,  True, False,  True])

In [16]:
f[condition]

array([1, 3, 3])